# ruff: noqa: E501
"""universal ai intake and exercise domain

Revision ID: 20260805_0003
Revises: 20260805_0002
Create Date: 2026-08-05 23:54:23.238565
"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "20260805_0003"
down_revision: str | None = "20260805_0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "exercise_metric_definitions",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column(
            "allowed_units_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("observation_projection_code", sa.String(length=100), nullable=True),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_metric_definitions")),
        sa.UniqueConstraint("code", name=op.f("uq_exercise_metric_definitions_code")),
    )
    op.create_table(
        "exercise_types",
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_types")),
        sa.UniqueConstraint("code", name=op.f("uq_exercise_types_code")),
    )
    op.create_table(
        "ai_intake_requests",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("submitted_by_user_account_id", sa.Uuid(), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("processing_run_id", sa.Uuid(), nullable=True),
        sa.Column("input_modality", sa.String(length=50), nullable=False),
        sa.Column("intake_purpose", sa.String(length=100), nullable=False),
        sa.Column("user_context_text", sa.Text(), nullable=True),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("prompt_template_name", sa.String(length=255), nullable=False),
        sa.Column("prompt_version", sa.String(length=50), nullable=False),
        sa.Column("output_schema_version", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column(
            "raw_model_response_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("submission_summary", sa.Text(), nullable=True),
        sa.Column(
            "unresolved_content",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("overall_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("error_code", sa.String(length=100), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_ai_intake_requests_person_id_persons")
        ),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_ai_intake_requests_processing_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
            name=op.f("fk_ai_intake_requests_source_artifact_id_source_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["submitted_by_user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_ai_intake_requests_submitted_by_user_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_intake_requests")),
    )
    op.create_index(
        "ix_ai_intake_person_created",
        "ai_intake_requests",
        ["person_id", "created_at"],
        unique=False,
    )
    op.create_index("ix_ai_intake_status", "ai_intake_requests", ["status"], unique=False)
    op.create_table(
        "ai_processing_consents",
        sa.Column("ai_intake_request_id", sa.Uuid(), nullable=False),
        sa.Column("user_account_id", sa.Uuid(), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=False),
        sa.Column("provider_name", sa.String(length=100), nullable=False),
        sa.Column("model_name", sa.String(length=255), nullable=False),
        sa.Column("purpose", sa.String(length=100), nullable=False),
        sa.Column("policy_version", sa.String(length=50), nullable=False),
        sa.Column(
            "consented_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["ai_intake_request_id"],
            ["ai_intake_requests.id"],
            name=op.f("fk_ai_processing_consents_ai_intake_request_id_ai_intake_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
            name=op.f("fk_ai_processing_consents_source_artifact_id_source_artifacts"),
        ),
        sa.ForeignKeyConstraint(
            ["user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_ai_processing_consents_user_account_id_user_accounts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_processing_consents")),
    )
    op.create_index(
        "ix_ai_consent_user_time",
        "ai_processing_consents",
        ["user_account_id", "consented_at"],
        unique=False,
    )
    op.create_table(
        "proposed_health_fact_groups",
        sa.Column("ai_intake_request_id", sa.Uuid(), nullable=False),
        sa.Column("processing_run_id", sa.Uuid(), nullable=False),
        sa.Column("subject_person_id", sa.Uuid(), nullable=False),
        sa.Column("group_identifier", sa.String(length=255), nullable=False),
        sa.Column("group_type", sa.String(length=100), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ai_intake_request_id"],
            ["ai_intake_requests.id"],
            name=op.f("fk_proposed_health_fact_groups_ai_intake_request_id_ai_intake_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_proposed_health_fact_groups_processing_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_person_id"],
            ["persons.id"],
            name=op.f("fk_proposed_health_fact_groups_subject_person_id_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposed_health_fact_groups")),
        sa.UniqueConstraint(
            "ai_intake_request_id", "group_identifier", name="uq_intake_fact_group"
        ),
    )
    op.create_index(
        "ix_fact_groups_run_type",
        "proposed_health_fact_groups",
        ["processing_run_id", "group_type"],
        unique=False,
    )
    op.create_table(
        "exercise_sessions",
        sa.Column("person_id", sa.Uuid(), nullable=False),
        sa.Column("exercise_type_id", sa.Uuid(), nullable=False),
        sa.Column("source_artifact_id", sa.Uuid(), nullable=True),
        sa.Column("processing_run_id", sa.Uuid(), nullable=True),
        sa.Column("fact_group_id", sa.Uuid(), nullable=True),
        sa.Column("entered_by_user_account_id", sa.Uuid(), nullable=False),
        sa.Column("confirmed_by_user_account_id", sa.Uuid(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("ended_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_seconds", sa.Integer(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("source_measurement_reliability", sa.String(length=50), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_exercise_sessions_confirmed_by_user_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["entered_by_user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_exercise_sessions_entered_by_user_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["exercise_type_id"],
            ["exercise_types.id"],
            name=op.f("fk_exercise_sessions_exercise_type_id_exercise_types"),
        ),
        sa.ForeignKeyConstraint(
            ["fact_group_id"],
            ["proposed_health_fact_groups.id"],
            name=op.f("fk_exercise_sessions_fact_group_id_proposed_health_fact_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["person_id"], ["persons.id"], name=op.f("fk_exercise_sessions_person_id_persons")
        ),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_exercise_sessions_processing_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["source_artifact_id"],
            ["source_artifacts.id"],
            name=op.f("fk_exercise_sessions_source_artifact_id_source_artifacts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_sessions")),
        sa.UniqueConstraint("fact_group_id", name=op.f("uq_exercise_sessions_fact_group_id")),
    )
    op.create_index(
        "ix_exercise_sessions_person_time",
        "exercise_sessions",
        ["person_id", "started_at"],
        unique=False,
    )
    op.create_table(
        "proposed_health_facts",
        sa.Column("processing_run_id", sa.Uuid(), nullable=False),
        sa.Column("candidate_record_id", sa.Uuid(), nullable=False),
        sa.Column("fact_group_id", sa.Uuid(), nullable=True),
        sa.Column("subject_person_id", sa.Uuid(), nullable=False),
        sa.Column("fact_category", sa.String(length=100), nullable=False),
        sa.Column("fact_code", sa.String(length=150), nullable=False),
        sa.Column("display_name", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.String(length=50), nullable=True),
        sa.Column("numeric_value", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("text_value", sa.Text(), nullable=True),
        sa.Column("boolean_value", sa.Boolean(), nullable=True),
        sa.Column("date_value", sa.Date(), nullable=True),
        sa.Column("datetime_value", sa.DateTime(timezone=True), nullable=True),
        sa.Column("original_value_text", sa.Text(), nullable=True),
        sa.Column("unit", sa.String(length=100), nullable=True),
        sa.Column("original_unit", sa.String(length=100), nullable=True),
        sa.Column("reference_range_low", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reference_range_high", sa.Numeric(precision=20, scale=8), nullable=True),
        sa.Column("reference_range_text", sa.String(length=500), nullable=True),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("observed_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source_label", sa.String(length=255), nullable=True),
        sa.Column("source_locator", sa.String(length=500), nullable=True),
        sa.Column("interpretation_notes", sa.Text(), nullable=True),
        sa.Column("canonical_target_type", sa.String(length=100), nullable=True),
        sa.Column("canonical_status", sa.String(length=50), nullable=False),
        sa.Column(
            "original_proposal_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("confirmed_by_user_account_id", sa.Uuid(), nullable=True),
        sa.Column("confirmed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("promoted_record_type", sa.String(length=100), nullable=True),
        sa.Column("promoted_record_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(CASE WHEN numeric_value IS NULL THEN 0 ELSE 1 END + CASE WHEN text_value IS NULL THEN 0 ELSE 1 END + CASE WHEN boolean_value IS NULL THEN 0 ELSE 1 END + CASE WHEN date_value IS NULL THEN 0 ELSE 1 END + CASE WHEN datetime_value IS NULL THEN 0 ELSE 1 END) <= 1",
            name=op.f("ck_proposed_health_facts_at_most_one_typed_value"),
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR (confidence >= 0 AND confidence <= 1)",
            name=op.f("ck_proposed_health_facts_confidence_range"),
        ),
        sa.ForeignKeyConstraint(
            ["candidate_record_id"],
            ["candidate_records.id"],
            name=op.f("fk_proposed_health_facts_candidate_record_id_candidate_records"),
        ),
        sa.ForeignKeyConstraint(
            ["confirmed_by_user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_proposed_health_facts_confirmed_by_user_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["fact_group_id"],
            ["proposed_health_fact_groups.id"],
            name=op.f("fk_proposed_health_facts_fact_group_id_proposed_health_fact_groups"),
        ),
        sa.ForeignKeyConstraint(
            ["processing_run_id"],
            ["processing_runs.id"],
            name=op.f("fk_proposed_health_facts_processing_run_id_processing_runs"),
        ),
        sa.ForeignKeyConstraint(
            ["subject_person_id"],
            ["persons.id"],
            name=op.f("fk_proposed_health_facts_subject_person_id_persons"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposed_health_facts")),
        sa.UniqueConstraint(
            "candidate_record_id", name=op.f("uq_proposed_health_facts_candidate_record_id")
        ),
    )
    op.create_index(
        "ix_proposed_facts_group", "proposed_health_facts", ["fact_group_id"], unique=False
    )
    op.create_index(
        "ix_proposed_facts_run_status",
        "proposed_health_facts",
        ["processing_run_id", "canonical_status"],
        unique=False,
    )
    op.create_table(
        "exercise_metrics",
        sa.Column("exercise_session_id", sa.Uuid(), nullable=False),
        sa.Column("metric_definition_id", sa.Uuid(), nullable=False),
        sa.Column("numeric_value", sa.Numeric(precision=20, scale=8), nullable=False),
        sa.Column("unit", sa.String(length=100), nullable=False),
        sa.Column("extraction_confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("source_measurement_reliability", sa.String(length=50), nullable=False),
        sa.Column("user_confirmed", sa.Boolean(), nullable=False),
        sa.Column("proposed_health_fact_id", sa.Uuid(), nullable=True),
        sa.Column("projected_observation_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["exercise_session_id"],
            ["exercise_sessions.id"],
            name=op.f("fk_exercise_metrics_exercise_session_id_exercise_sessions"),
        ),
        sa.ForeignKeyConstraint(
            ["metric_definition_id"],
            ["exercise_metric_definitions.id"],
            name=op.f("fk_exercise_metrics_metric_definition_id_exercise_metric_definitions"),
        ),
        sa.ForeignKeyConstraint(
            ["projected_observation_id"],
            ["health_observations.id"],
            name=op.f("fk_exercise_metrics_projected_observation_id_health_observations"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_health_fact_id"],
            ["proposed_health_facts.id"],
            name=op.f("fk_exercise_metrics_proposed_health_fact_id_proposed_health_facts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exercise_metrics")),
        sa.UniqueConstraint(
            "exercise_session_id", "metric_definition_id", name="uq_exercise_metric"
        ),
    )
    op.create_table(
        "proposed_fact_revisions",
        sa.Column("proposed_health_fact_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_account_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column(
            "before_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "after_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"),
            nullable=True,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_account_id"],
            ["user_accounts.id"],
            name=op.f("fk_proposed_fact_revisions_actor_user_account_id_user_accounts"),
        ),
        sa.ForeignKeyConstraint(
            ["proposed_health_fact_id"],
            ["proposed_health_facts.id"],
            name=op.f("fk_proposed_fact_revisions_proposed_health_fact_id_proposed_health_facts"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_proposed_fact_revisions")),
    )
    op.create_index(
        "ix_fact_revisions_fact_time",
        "proposed_fact_revisions",
        ["proposed_health_fact_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_fact_revisions_fact_time", table_name="proposed_fact_revisions")
    op.drop_table("proposed_fact_revisions")
    op.drop_table("exercise_metrics")
    op.drop_index("ix_proposed_facts_run_status", table_name="proposed_health_facts")
    op.drop_index("ix_proposed_facts_group", table_name="proposed_health_facts")
    op.drop_table("proposed_health_facts")
    op.drop_index("ix_exercise_sessions_person_time", table_name="exercise_sessions")
    op.drop_table("exercise_sessions")
    op.drop_index("ix_fact_groups_run_type", table_name="proposed_health_fact_groups")
    op.drop_table("proposed_health_fact_groups")
    op.drop_index("ix_ai_consent_user_time", table_name="ai_processing_consents")
    op.drop_table("ai_processing_consents")
    op.drop_index("ix_ai_intake_status", table_name="ai_intake_requests")
    op.drop_index("ix_ai_intake_person_created", table_name="ai_intake_requests")
    op.drop_table("ai_intake_requests")
    op.drop_table("exercise_types")
    op.drop_table("exercise_metric_definitions")
    # ### end Alembic commands ###
